name: CICD - MAIN
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  ReUse:
    uses: anilkumarm429/roboshop-github-actions/.github/workflows/ci-main.yml@main
    with:
      appType: 'maven'


